In [1]:
# PYTHON PROGRAMMING FUNDAMENTALS

# arithemtic operation(s)
100 // 7

14

In [45]:
# variables
cost_of_ice_bag = 1.25
profit_margin = 0.2
number_of_bags = 500

profit_per_bag = cost_of_ice_bag * profit_margin

total_profit = number_of_bags * profit_per_bag
print("Total profit is in €", total_profit)

Total profit is in € 125.0


In [1]:
couter = 10
couter += 1
print(couter)

11


In [27]:
# data types
is_today_morning = False

type(is_today_morning)

bool

In [3]:
arr_example = ["apple", "juice", "tonic"]

type(arr_example)

list

In [41]:
pi_no = 3.14159

type(pi_no)

float

In [49]:
# cast
int(pi_no)

3

In [51]:
str(pi_no)

'3.14159'

In [73]:
multiline_string = """abcdefgh"""

multiline_string[0]

'a'

In [95]:
list(multiline_string)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [97]:
len(multiline_string)

8

In [99]:
# string methods
"saturday".capitalize()

'Saturday'

In [101]:
"monday".upper()

'MONDAY'

In [103]:
"Monday".replace("Monday", "Sunday")

'Sunday'

In [105]:
"       Monday      ".strip()

'Monday'

In [149]:
# list (arrays - mutable)
fruits = ['apple', 'banana', 'cherry']
#len(fruits)

fruits[0] = 'lemon'

fruits.append('dates')
fruits.remove('dates')
fruits.pop(1)
fruits.copy()

print(fruits)

['lemon', 'cherry']


In [141]:
a_list = [23, 'hello', None, 3.14, fruits, 3 <= 5]

a_list[2:5]

[None, 3.14, ['lemon', 'banana', 'cherry']]

In [153]:
# tuple (immutable)
tuple_arr = (1, 2, 3, 4, 5)

In [65]:
# dictinary
person1 = {
    'name': 'John Doe',
    'age': 32,
    'married': True
}

person1['name'] = 'Ted'
person1

person1.keys()
person1.values()
person1.items()

dict_items([('name', 'Ted'), ('age', 32), ('married', True)])

In [67]:
# BRANSHING LOOPS AND FUNCTIONS

#if, else, elif
a, b, c = True, False, True

if a and c:
    print("Both a and c are True.")
    
if b or c:
    print("Either b or c is True.")
    
if not b:
    print("b is False (NOT condition).")

Both a and c are True.
Either b or c is True.
b is False (NOT condition).


In [69]:
x_number = 34

if x_number % 2:
    print("The given number {} is even".format(x_number))
elif x_number % 1 == 0:
    print("This number {} is odd".format(x_number))
else:
     print("Other error")


This number 34 is odd


In [24]:
# while
i = 1

while i < 6:
     print(f"The result is {i}")
     i += 1
     if i == 3:
         print(f"Stop at number {i}")
         break

The result is 1
The result is 2
Stop at number 3


In [32]:
# for
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

for day in days:
    print(day)

Monday
Tuesday
Wednesday
Thursday
Friday


In [34]:
for char in 'Monday':
    print(char)

M
o
n
d
a
y


In [52]:
person = {
    'name': 'John Doe',
    'age': 32,
    'married': True
}

for value in person.values():
    print(value)

John Doe
32
True


In [56]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [62]:
days = ['Monday', 'Tuesday', 'Wednesday']
fruits = ['apple', 'banana', 'apple']

for day in days:
    for fruit in fruits:
        print(day, fruit)

Monday apple
Monday banana
Monday apple
Tuesday apple
Tuesday banana
Tuesday apple
Wednesday apple
Wednesday banana
Wednesday apple


In [1]:
# functions
def sayHello(name):
    print(f"Hello {name} there")

sayHello("Johnny")

Hello Johnny there


In [86]:
def myFun(a,b):
    result = a + b
    print(f"the result is {result}")
    # return result

myFun(3, 5)

the result is 8


In [88]:
import math

In [114]:
math.ceil(1.2)

2

In [116]:
round(4.5)

4

In [118]:
try:
    print(round(4.5))
except:
    print("Error")

4


In [8]:
#NUMPY

# numpy Arrays
# !pip install numpy

weight[0]
import numpy as np

height = np.array([73, 67, 43])

height

array([73, 67, 43])

In [30]:
weight = np.array([0.3, 0.2, 0.5])

weight

array([0.3, 0.2, 0.5])

In [32]:
weight[0]

0.3

In [38]:
# operating on numpy array

# (weight * height).sum()
np.dot(weight, height)

56.8

In [59]:
# multi-dimensional numpy array

climate_data = np.array(
    [[73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]]
)

climate_data.shape

(5, 3)

In [57]:
weight.shape

(3,)

In [71]:
arr3 = np.array(
        [[[0, 0, 0, 0], 
        [0, 0, 0, 0], 
        [0, 0, 0, 0]],
        
        [[0, 0, 0, 0], 
        [0, 0, 0, 0], 
        [0, 0, 0, 0]]]
)

arr3.shape

(2, 3, 4)

In [73]:
# climate_data @ weight
np.matmul(climate_data, weight)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [81]:
import urllib.request

urllib.request.urlretrieve('https://raw.githubusercontent.com/the-stranger-web/jovian_Data_Analyst/refs/heads/main/italy-covid-daywise.csv', 'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1e32195b470>)

In [91]:
climate_data_file = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

climate_data_file

array([[        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.0000e+00,  0.0000e+00,         nan],
       [        nan,  0.

In [93]:
climate_data_file.shape

(248, 4)

In [121]:
weights = np.array([0.3, 0.2, 0.5])

yields = climate_data_file @ weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [129]:
climate_results = np.concatenate((climate_data_file, yields.reshape(248,1)), axis=1)

NameError: name 'yields' is not defined

In [127]:
np.savetxt('climate_results.txt', climate_results, fmt='%.2f', header='temperature, rainfall, humidity, Yeaild_apples', comments='')

NameError: name 'climate_results' is not defined

In [149]:
# array indexing and slicing
arr4 = np.array(
        [[[1, 2, 3, 4], 
        [5, 6, 7, 8], 
        [9, 10, 11, 12]],
        
        [[13, 14, 15, 16], 
        [17, 18, 19, 20], 
        [21, 22, 23, 24]]]
)

arr4.shape

(2, 3, 4)

In [151]:
arr4[1,1,2]

19

In [153]:
arr4[1:, 0:1, :2]

array([[[13, 14]]])

In [159]:
arr4[1:1,2]

array([], shape=(0, 4), dtype=int32)

In [161]:
# creating numpy arrays
# np.ones(3, 2)
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [163]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
np.random.rand(5)
#np.random.rand(2, 3)

array([0.56115557, 0.23548612, 0.7793304 , 0.76528848, 0.11664024])

In [171]:
# fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [173]:
# range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [175]:
# equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [3]:
# files

import os

os.getcwd()

'C:\\Users\\Veronika'

In [5]:
os.listdir('.')

['.anaconda',
 '.bash_history',
 '.conda',
 '.condarc',
 '.continuum',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.ms-ad',
 '.viminfo',
 '.vscode',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'climate.txt',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'PycharmProjects',
 'PythonTut.ipynb',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos']

In [22]:
os.makedirs('./data', exist_ok=True)

In [26]:
'data' in os.listdir('.')

True

In [46]:
import urllib.request

url1 ='https://hub.jovian.ml/wp-content/uploads/2020/08/loans1.txt'

In [70]:
urllib.request.urlretrieve(url1,'./data/loans1.txt')
urllib.request.urlretrieve(url2,'./data/loans2.txt')
urllib.request.urlretrieve(url3,'./data/loans3.txt')

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [58]:
os.listdir('./data')

[]

In [60]:
file1 = open('./data/loans1.txt', mode='r')

FileNotFoundError: [Errno 2] No such file or directory: './data/loans1.txt'

In [62]:
file1_contents = file1.read()

NameError: name 'file1' is not defined

In [66]:
print(file1_contents)

NameError: name 'file1_contents' is not defined

In [68]:
file1.close()

NameError: name 'file1' is not defined

In [72]:
# reading file by line

file3 = open('./data/loans3.txt', mode='r')
file_contents3 = file3.readlines()
file_contents3

FileNotFoundError: [Errno 2] No such file or directory: './data/loans3.txt'